-- Script de referência para estrutura esperada pela API.
-- Ajuste tipos/tamanhos conforme padrão do seu Oracle.

-- Tabela USUARIOS
-- Campos usados: ID, NOME, EMAIL, SENHA, PERFIL, UNIDADE, AVATAR_URL, CRIADO_EM

-- Tabela IDEIAS
-- Campos usados: ID, TITULO, DESCRICAO, CATEGORIA, OPERADOR_ID, OPERADOR_NOME,
-- UNIDADE, STATUS, PRIORIDADE, COMENTARIO_GERENTE, APROVADA_POR, APROVADA_EM,
-- CRIADO_EM, ATUALIZADO_EM

-- Tabela PROJETOS
-- Campos usados: ID, IDEIA_ID, TITULO, OBJETIVO, ETAPA, STATUS, GERENTE_ID,
-- DATA_INICIO, DATA_FIM_META, DATA_FIM_REAL, INVESTIMENTO, RETORNO_FINANCEIRO,
-- REDUCAO_CUSTO, GANHO_PRODUTIVIDADE_PCT, LUCRO, ROI, PROGRESSO_PCT,
-- CRIADO_EM, ATUALIZADO_EM

-- Tabela DIRETRIZES
-- Campos usados: ID, TITULO, DESCRICAO, PILAR, VALIDO_DE, VALIDO_ATE,
-- STATUS, CRIADO_POR, CRIADO_EM, ATUALIZADO_EM

-- Tabela METRICAS_PAINEL (opcional)
-- Campos usados: TOTAL_IDEIAS, IDEIAS_APROVADAS, PROJETOS_ATIVOS,
-- INVESTIMENTO_TOTAL, RETORNO_TOTAL, LUCRO_TOTAL, REDUCAO_CUSTO_TOTAL,
-- MEDIA_GANHO_PRODUTIVIDADE, ROI_GLOBAL, PERIODO_INICIO

