-- Drop tables if they exist (for H2 re-runs)
DROP TABLE IF EXISTS METRICAS_PAINEL;
DROP TABLE IF EXISTS PROJETOS;
DROP TABLE IF EXISTS IDEIAS;
DROP TABLE IF EXISTS DIRETRIZES;
DROP TABLE IF EXISTS USUARIOS;

-- Tabela USUARIOS
CREATE TABLE USUARIOS (
    ID VARCHAR(100) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    PERFIL VARCHAR(50) NOT NULL,
    UNIDADE VARCHAR(100),
    AVATAR_URL VARCHAR(500),
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela DIRETRIZES
CREATE TABLE DIRETRIZES (
    ID VARCHAR(100) PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO CLOB NOT NULL,
    PILAR VARCHAR(100) NOT NULL,
    VALIDO_DE TIMESTAMP,
    VALIDO_ATE TIMESTAMP,
    STATUS VARCHAR(50) NOT NULL,
    CRIADO_POR VARCHAR(100),
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela IDEIAS
CREATE TABLE IDEIAS (
    ID VARCHAR(100) PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO CLOB NOT NULL,
    CATEGORIA VARCHAR(100) NOT NULL,
    OPERADOR_ID VARCHAR(100) NOT NULL,
    OPERADOR_NOME VARCHAR(255),
    UNIDADE VARCHAR(100),
    STATUS VARCHAR(50) NOT NULL,
    PRIORIDADE VARCHAR(50),
    COMENTARIO_GERENTE CLOB,
    APROVADA_POR VARCHAR(100),
    APROVADA_EM TIMESTAMP,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_IDEIA_USER FOREIGN KEY (OPERADOR_ID) REFERENCES USUARIOS(ID)
);

-- Tabela PROJETOS
CREATE TABLE PROJETOS (
    ID VARCHAR(100) PRIMARY KEY,
    IDEIA_ID VARCHAR(100),
    TITULO VARCHAR(255) NOT NULL,
    OBJETIVO CLOB NOT NULL,
    ETAPA VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    GERENTE_ID VARCHAR(100) NOT NULL,
    DATA_INICIO TIMESTAMP NOT NULL,
    DATA_FIM_META TIMESTAMP NOT NULL,
    DATA_FIM_REAL TIMESTAMP,
    INVESTIMENTO NUMBER(15,2) DEFAULT 0,
    RETORNO_FINANCEIRO NUMBER(15,2) DEFAULT 0,
    REDUCAO_CUSTO NUMBER(15,2) DEFAULT 0,
    GANHO_PRODUTIVIDADE_PCT NUMBER(5,2) DEFAULT 0,
    LUCRO NUMBER(15,2) DEFAULT 0,
    ROI NUMBER(15,2) DEFAULT 0,
    PROGRESSO_PCT NUMBER(3) DEFAULT 0,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PROJETO_IDEIA FOREIGN KEY (IDEIA_ID) REFERENCES IDEIAS(ID),
    CONSTRAINT FK_PROJETO_USER FOREIGN KEY (GERENTE_ID) REFERENCES USUARIOS(ID)
);

-- Tabela METRICAS_PAINEL
CREATE TABLE METRICAS_PAINEL (
    ID VARCHAR(100) PRIMARY KEY,
    TOTAL_IDEIAS NUMBER DEFAULT 0,
    IDEIAS_APROVADAS NUMBER DEFAULT 0,
    PROJETOS_ATIVOS NUMBER DEFAULT 0,
    INVESTIMENTO_TOTAL NUMBER(18,2) DEFAULT 0,
    RETORNO_TOTAL NUMBER(18,2) DEFAULT 0,
    LUCRO_TOTAL NUMBER(18,2) DEFAULT 0,
    REDUCAO_CUSTO_TOTAL NUMBER(18,2) DEFAULT 0,
    MEDIA_GANHO_PRODUTIVIDADE NUMBER(5,2) DEFAULT 0,
    ROI_GLOBAL NUMBER(10,2) DEFAULT 0,
    PERIODO_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
